sudo: true

language: python

cache:
    directories:
        - $HOME/.ccache
        - $HOME/.cache/pip
        - $HOME/.cache/matplotlib

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - sudo apt-get update
    - sudo apt-get install ncbi-blast+

install:
    - pip install --upgrade pip wheel
    - pip install nose
    - pip install numpy
    - pip install pandas
    - pip install matplotlib
    - pip install biopython
    - pip install jinja2
    - pip install .

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 10


script:
    - nosetests -v

